# Copyright 2024 The zb Authors
# SPDX-License-Identifier: MIT

name: Test
on:
  push:
  pull_request:
jobs:
  cli:
    name: Test CLI
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: internal/ui/package.json
      - name: 'Set TMP to D:\ drive'
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          "TMP=D:\tmp" | Out-File -Append -FilePath ${env:GITHUB_ENV} -Encoding ascii
      - name: Build UI
        run: go generate ./internal/ui
      - name: Run tests
        run: go test -mod=readonly -race ./...
