# Copyright 2024 The zb Authors
# SPDX-License-Identifier: MIT

name: Test
on:
  push:
  pull_request:
jobs:
  cli:
    name: Test CLI
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: internal/ui/package.json
      - name: Build UI
        run: go generate ./internal/ui
      - name: Run tests
        if: runner.os != 'Linux' && runner.os != 'Windows'
        run: go test -mod=readonly -timeout=10m ./...
      - name: Run tests with race detector
        if: runner.os == 'Linux'
        run: go test -mod=readonly -timeout=10m -race ./...
      # TODO(#304): Change timeout back to default.
      - name: Run tests with a long timeout
        if: runner.os == 'Windows'
        run: go test -mod=readonly -timeout=30m ./...
